<?php

namespace DesignPattern\Structural\Decorator\Decorators;

use DesignPattern\Structural\Decorator\Notifier;
use DesignPattern\Structural\Decorator\NotifierDecorator;

class SmsNotifierDecorator extends NotifierDecorator
{
    protected string $phone;

    /**
     * @param string $phone
     */
    public function __construct(string $phone, Notifier $notifier)
    {
        parent::__construct($notifier);
        $this->phone = $phone;
    }

    public function notify()
    {
        parent::notify(); // TODO: Change the autogenerated stub
        $this->sendSms();
    }

    private function sendSms()
    {
        echo "Sending Sms To {$this->phone}\n";
        echo "You latest Operation was Executed Successfully\n";
    }
}